### ISSUE TITLE
set up email service

### ISSUE THREAD

**Issue by bion** [bion/superdelegation#16]

**Comment by dbalatero** [comment]
@bion fyi

Postmark 50k messages/month - $75/mo or $0.00150 per email
Sendgrid 40k /month - $9.99/mo or $0.00025 per email
SES $0.10 per 1000 emails - or $0.00010 per email

**Comment by dbalatero** [comment]
on SES, 100k emails would run us about $10

**Comment by bion** [comment]
@dbalatero 

patrick has some experience with this stuff and says we'll almost immediately get added to spam lists if we start bulk-emailing.

**Comment by dbalatero** [comment]
Does this mean we should stick to web forms?

**Comment by bion** [comment]
i think so

**Comment by dbalatero** [comment]
tight
