### ISSUE TITLE
add Delegates::WA::Cantwell class

### ISSUE THREAD

**Issue by bion** [bion/superdelegation#21]

**Comment by philipbjorge** [comment]
Maria Cantwell's form requires JS.
Thoughts on what to use?

@dbalatero @bion @scottmacphersonmusic @andyjac

**Comment by dbalatero** [comment]
Can one use poltergeist in production outside of test? I've never done it but it might work?

**Comment by philipbjorge** [comment]
I'll look into it -- It looks like you can, but we'll probably be limited to running one delayed job at a time due to memory constraints? I'll get an initial implementation done tonight probably and get it out for review...

**Comment by dbalatero** [comment]
@philipbjorge how about capturing the JS AJAX request in the Network tab in Chrome and then spoofing that? That might be cheaper and doable with `httparty` or something?

**Comment by dbalatero** [comment]
There's a neat feature that will dump a request to `curl` command line params in Chrome too, which might reveal any auth headers or anything like that.

**Comment by philipbjorge** [comment]
@dbalatero -- So you're proposing just making the HTTP request manually (i.e. watching for the POST when I submit the form myself)?
I'll look into that as well.

**Comment by dbalatero** [comment]
Yeah totally, that might get around having to use a JS browser.
