### ISSUE TITLE
add Delegates::WA::Larsen class

### ISSUE THREAD

**Issue by bion** [bion/superdelegation#23]

**Comment by dbalatero** [comment]
USPS has an API for address verification, but it requires you to be shipping packages with them as part of their TOS.

http://stackoverflow.com/questions/15033361/get-9-digit-zip-code-from-5-digit-zip-code-programmatic-api

https://smartystreets.com/features this only has 250 free/mo

http://www.unitedstateszipcodes.org/zip-code-database -> csv database

OR finally

http://www.unitedstateszipcodes.org -> if I put in my address here it seems to give us +4 zip back. Just have to figure out where the data comes from.
