### ISSUE TITLE
1 job per DelegateMessage

### ISSUE THREAD

**Issue by bion** [bion/superdelegation#51]
Currently if a message fails to send to one delegate, the job is failed for all of them such that retrying will resend to all of the delegates.

**Comment by dbalatero** [comment]
@bion this isn't how we initially designed it – did something change?

Each `SendMessageJob` is scoped to its recipient: https://github.com/bion/superdelegation/blob/6a5224f0eaf3f25c57e6b41290d654d39c4a023b/app/jobs/send_message_job.rb#L7

Retrying the single job should only retry it for the given `Delegates::WA::<name>` class

**Comment by bion** [comment]
@dbalatero haaaaaaa yeah you're right
