### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by robhanlon22** [bion/superdelegation#68]
ideas here? http://collectiveidea.com/blog/archives/2016/01/12/lets-encrypt-with-a-rails-app-on-heroku/
maybe this plugin? https://github.com/lgromanowski/letsencrypt-plugin

**Comment by bion** [comment]
yes cool

**Comment by ohwillie** [comment]
i can install that plugin but one of the heroku app owners will have to do the rest, also it will cost $

**Comment by bion** [comment]
@ohwillie added you to the heroku account
